server {
    listen 80;
    server_name _;

    client_max_body_size 500m;

    # Vue
    location / {
        proxy_pass http://127.0.0.1:7999;
    }

    # Python API
    location /api/ {
        proxy_pass http://127.0.0.1:8000;
    }

    location /static/uploads/ {
        proxy_pass http://127.0.0.1:8000;
        expires 7d;
        add_header Cache-Control "public";
    }
}
